### ISSUE TITLE
Incompatibility with Kafka-connect

### ISSUE THREAD

**Issue by inneractive-opensrc** [ovotech/kafka-serialization#16]
Hi
The library is very useful for scala developer but there is an issue with the idea to put in the payload the version of the schema. it's become incompatible with other Confluent platform.
When I push the message using avroBinarySchemaIdSerializer I'm able to consume the message with the corresponding Deserializer but kafka-connect failed I get this error
```
org.apache.kafka.common.errors.SerializationException: Error retrieving Avro schema for id 256
Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Schema not found; error code: 40403

```
Is there any other way to use the library and keep the compatibility with kafka-connect ?
Thanks

**Comment by filosganga** [comment]
Kakfa connect should be compatible, we are using it with this library. This error looks like the schema registry you are connected to seems to be different from the one used when the message has been produced.
