### ISSUE TITLE
API inconsistencies

### ISSUE THREAD

**Issue by oliverlockwood** [ovotech/kafka-serialization#26]
There are a couple of unnecessary API inconsistencies:
-  In a few places, such as [here](https://github.com/ovotech/kafka-serialization/blob/master/avro4s/src/main/scala/com/ovoenergy/kafka/serialization/avro4s/Avro4sSerialization.scala#L164-L174), a parameter named `includeFormatByte` is used.
-  In a few places, such as [here](https://github.com/ovotech/kafka-serialization/blob/master/avro4s/src/main/scala/com/ovoenergy/kafka/serialization/avro4s/Avro4sSerialization.scala#L82-L95), the equivalent parameter is named `includesFormatByte` instead.

I'm happy to raise a PR to correct this, if you tell me which of the two you'd like to standardise towards.

**Comment by filosganga** [comment]
Hi Oliver,
It is a very good point. I am not sure which form is preferred as I am not a native English speaker. 

I think it depends on the use cases, if the method is named `doThis` then the `includeFormatByte` style would be preferred as both are imperative style.

If the method is instead a sort of declarative type `stuff` then the `includesFormatByte` seems preferable to me.

Given the nature of this library methods, I think the `includesFormatByte` would be better. If you do agree, please open PR to fix it.

Thanks

**Comment by oliverlockwood** [comment]
@filosganga Thanks for the quick reply.  I agree with your assessment; I'll raise a PR to fix this tomorrow.

**Comment by cb372** [comment]
I don't have any strong opinions on this, but just for the record, the use of different parameter names was deliberate.

For serializers, it was `includeFormatByte`, meaning "I want to serialize something into an Avro message and I want to *include* a format byte."

For deserializers, it was `includesFormatByte`, meaning "I want to deserialize from this binary message, which *includes* a format byte."

I probably should have left a comment somewhere to point this out.

**Comment by filosganga** [comment]
@cb372 the rationale behind it makes sense now. 

The problem I see is that the method name is not a verb but a substantive (and I am not sure if it is a good practice). I feel that using the 3rd person singular is a better fit in this case.

**Comment by filosganga** [comment]
@oliverlockwood It has been released in the 0.3.2 version
