### ISSUE TITLE
NullPointerException in CirceSerialization

### ISSUE THREAD

**Issue by perryao** [ovotech/kafka-serialization#37]
Kafka Deserializers need to handle null data, as outlined in this comment: https://github.com/apache/kafka/blob/1.0/clients/src/main/java/org/apache/kafka/common/serialization/Deserializer.java#L43.

Right now my streams app is crashing because data is null and is being passed to the string constructor

**Comment by perryao** [comment]
https://github.com/ovotech/kafka-serialization/blob/master/circe/src/main/scala/com/ovoenergy/kafka/serialization/circe/CirceSerialization.scala#L36

Is the line that can throw an NPE

**Comment by filosganga** [comment]
Thanks for reporting the issue. The best approach, in my opinion, is to provide another general deserializer that returns `Option[T]` so that we can wrap a `Deserializer[T]`.
