### ISSUE TITLE
Unable to configure underlying KafkaAvroSerializer

### ISSUE THREAD

**Issue by tjheslin1** [ovotech/kafka-serialization#39]
Confluent's `schema-registry` version  `4.0.0`s contains a new property: `auto.register.schemas` which we intend to use.

We would like to add the ability to configure the underlying `KafkaAvroSerializer`. In our specific case we will be able to set `auto.register.schemas` to `false` and anyone else would be able to configure the serializer how they see fit.

Currently the underlying [kafkaAvroSerializer](https://github.com/ovotech/kafka-serialization/blob/master/avro4s/src/main/scala/com/ovoenergy/kafka/serialization/avro4s/Avro4sSerialization.scala#L229) is configured with a default. We do not have access to this serializer to configure it.

Calling `configure` on the serializer returned by `#avroBinarySchemaIdSerializer` is of no use as this method is purposely not implemented: 

```
// Keep in mind that for serializer built with this library Kafka will never call `configure`.
override def configure(configs: util.Map[String, _], isKey: Boolean): Unit = {}
```

**Comment by filosganga** [comment]
Hi,
Thanks for reporting this issue. I will take a look into that.

**Comment by tjheslin1** [comment]
I'm happy to raise a PR.

**Comment by filosganga** [comment]
This would be great, thanks
