### ISSUE TITLE
Support for avro4s 2+ 

### ISSUE THREAD

**Issue by DanieleSassoli** [ovotech/kafka-serialization#48]
We've updated avro4s to 2.0.2 as they've added support for deserialising instant values but this looks to have broken something.
```
[error] sbt.ForkMain$ForkError: java.lang.NoSuchMethodError: com.sksamuel.avro4s.ToRecord.apply(Ljava/lang/Object;)Lorg/apache/avro/generic/GenericRecord;
[error]         at com.ovoenergy.kafka.serialization.avro4s.Avro4sSerialization$$anonfun$avroBinarySchemaIdSerializerWithProps$1.apply(Avro4sSerialization.scala:284)
[error]         at com.ovoenergy.kafka.serialization.avro4s.Avro4sSerialization$$anonfun$avroBinarySchemaIdSerializerWithProps$1.apply(Avro4sSerialization.scala:283)
[error]         at com.ovoenergy.kafka.serialization.core.Serialization$$anon$1.serialize(Serialization.scala:41)```
```

From what we could gather it looks like the `apply` in avro4s 2+ `FromRecord` and `ToRecord` expects extra parameters from the one in 1.9.1.
1.9.1 
https://github.com/sksamuel/avro4s/blob/v1.9.1/avro4s-macros/src/main/scala/com/sksamuel/avro4s/ToRecord.scala#L204
v2.0.2
https://github.com/sksamuel/avro4s/blob/v2.0.2/avro4s-core/src/main/scala/com/sksamuel/avro4s/ToRecord.scala#L23

**Comment by filosganga** [comment]
Hi,
The work to support avro4s 2 is already in progress in one of the branch. Thanks for reporting. Will take a look at the specific issue you have raised

**Comment by lacarvalho91** [comment]
hi @filosganga, any update on this? the branch doesn't seem active - would be happy to look into contributing

**Comment by filosganga** [comment]
Fixed in https://github.com/ovotech/kafka-serialization/pull/56
