### ISSUE TITLE
Unable to download release 0.3.14 for kafka-serialization-avro4s_2.12

### ISSUE THREAD

**Issue by jocelyndrean** [ovotech/kafka-serialization#50]
Hi ! Thanks for this project :)
Little issue : I'm not able to find the version 0.3.14 for 2.12 https://dl.bintray.com/ovotech/maven/com/ovoenergy/kafka-serialization-avro4s_2.12/

Looks to be available on 2.11 : https://dl.bintray.com/ovotech/maven/com/ovoenergy/kafka-serialization-avro4s_2.11/

Have a nice day guys !
Jocelyn

**Comment by filosganga** [comment]
Hi,
Unfortunately, the 0.3.14 failed to deploy correctly. We may be able to deploy it again however it is also quite old, the new version 0.3.19 is binary compatible with that are you able to use the 0.3.19?

**Comment by jocelyndrean** [comment]
Yes, I switched to 0.3.19 :)
